ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MZ,MDL_MT,MDL_MW,MDL_MH2,MDL_MH3,MDL_MH1
     $ ,MDL_MB,MDL_MHC

      COMMON/MASSES/ MDL_MZ,MDL_MT,MDL_MW,MDL_MH2,MDL_MH3,MDL_MH1
     $ ,MDL_MB,MDL_MHC


      DOUBLE PRECISION MDL_WH1,MDL_WH2,MDL_WH3,MDL_WW,MDL_WT,MDL_WZ
     $ ,MDL_WHC

      COMMON/WIDTHS/ MDL_WH1,MDL_WH2,MDL_WH3,MDL_WW,MDL_WT,MDL_WZ
     $ ,MDL_WHC


      DOUBLE COMPLEX GC_187, GC_188, GC_190, GC_191, GC_204, GC_205,
     $  GC_207, GC_208, GC_351, GC_354, GC_360, GC_363, GC_414, GC_417
     $ , GC_423, GC_426, GC_520

      COMMON/COUPLINGS/ GC_187, GC_188, GC_190, GC_191, GC_204, GC_205
     $ , GC_207, GC_208, GC_351, GC_354, GC_360, GC_363, GC_414,
     $  GC_417, GC_423, GC_426, GC_520

