ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of 2HDM_NLO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_187 = ', GC_187
      WRITE(*,2) 'GC_188 = ', GC_188
      WRITE(*,2) 'GC_190 = ', GC_190
      WRITE(*,2) 'GC_191 = ', GC_191
      WRITE(*,2) 'GC_204 = ', GC_204
      WRITE(*,2) 'GC_205 = ', GC_205
      WRITE(*,2) 'GC_207 = ', GC_207
      WRITE(*,2) 'GC_208 = ', GC_208
      WRITE(*,2) 'GC_351 = ', GC_351
      WRITE(*,2) 'GC_354 = ', GC_354
      WRITE(*,2) 'GC_360 = ', GC_360
      WRITE(*,2) 'GC_363 = ', GC_363
      WRITE(*,2) 'GC_414 = ', GC_414
      WRITE(*,2) 'GC_417 = ', GC_417
      WRITE(*,2) 'GC_423 = ', GC_423
      WRITE(*,2) 'GC_426 = ', GC_426
      WRITE(*,2) 'GC_520 = ', GC_520
