ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MZ,MDL_MT,MDL_MW,MDL_MH2,MDL_MH3,MDL_MH1
     $ ,MDL_MB,MDL_MHC

      COMMON/MASSES/ MDL_MZ,MDL_MT,MDL_MW,MDL_MH2,MDL_MH3,MDL_MH1
     $ ,MDL_MB,MDL_MHC


      DOUBLE PRECISION MDL_WH1,MDL_WH2,MDL_WH3,MDL_WW,MDL_WT,MDL_WZ
     $ ,MDL_WHC

      COMMON/WIDTHS/ MDL_WH1,MDL_WH2,MDL_WH3,MDL_WW,MDL_WT,MDL_WZ
     $ ,MDL_WHC


      DOUBLE COMPLEX GC_235, GC_236, GC_238, GC_239, GC_252, GC_253,
     $  GC_255, GC_256, GC_352, GC_355, GC_361, GC_364, GC_415, GC_418
     $ , GC_424, GC_427, GC_321, GC_333, GC_374, GC_525

      COMMON/COUPLINGS/ GC_235, GC_236, GC_238, GC_239, GC_252, GC_253
     $ , GC_255, GC_256, GC_352, GC_355, GC_361, GC_364, GC_415,
     $  GC_418, GC_424, GC_427, GC_321, GC_333, GC_374, GC_525

