ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of 2HDM_NLO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_235 = ', GC_235
      WRITE(*,2) 'GC_236 = ', GC_236
      WRITE(*,2) 'GC_238 = ', GC_238
      WRITE(*,2) 'GC_239 = ', GC_239
      WRITE(*,2) 'GC_252 = ', GC_252
      WRITE(*,2) 'GC_253 = ', GC_253
      WRITE(*,2) 'GC_255 = ', GC_255
      WRITE(*,2) 'GC_256 = ', GC_256
      WRITE(*,2) 'GC_352 = ', GC_352
      WRITE(*,2) 'GC_355 = ', GC_355
      WRITE(*,2) 'GC_361 = ', GC_361
      WRITE(*,2) 'GC_364 = ', GC_364
      WRITE(*,2) 'GC_415 = ', GC_415
      WRITE(*,2) 'GC_418 = ', GC_418
      WRITE(*,2) 'GC_424 = ', GC_424
      WRITE(*,2) 'GC_427 = ', GC_427
      WRITE(*,2) 'GC_333 = ', GC_333
      WRITE(*,2) 'GC_374 = ', GC_374
      WRITE(*,2) 'GC_524 = ', GC_524
